### Import Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Load Dataset

In [4]:
dataset = pd.read_csv('customer_churn.csv')
X = dataset.iloc[:, [5,8,9,12,15,16,17,18]].values
y = dataset.iloc[:, -1].values

print("Feature Matrix (X):", X)
print("Target Vector (y):", y)

Feature Matrix (X): [[1 'DSL' 'No' ... 'Yes' 'Electronic check' 29.85]
 [34 'DSL' 'Yes' ... 'No' 'Mailed check' 56.95]
 [2 'DSL' 'Yes' ... 'Yes' 'Mailed check' 53.85]
 ...
 [11 'DSL' 'Yes' ... 'Yes' 'Electronic check' 29.6]
 [4 'Fiber optic' 'No' ... 'Yes' 'Mailed check' 74.4]
 [66 'Fiber optic' 'Yes' ... 'Yes' 'Bank transfer (automatic)' 105.65]]
Target Vector (y): ['No' 'No' 'Yes' ... 'No' 'Yes' 'No']


### Check for Missing Values

In [5]:
missing_values = dataset.isnull().sum()
print("Missing Values in Each Column:\n", missing_values)

Missing Values in Each Column:
 customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64


### Encode Categorical Data

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Encode the target variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

# Apply OneHotEncoding on specified columns in the feature matrix
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [1,2,3,4,5,6])],
    remainder='passthrough'
)
X = ct.fit_transform(X)

print("Encoded Feature Matrix (X):\n", X)
print("Encoded Target Vector (y):\n", y)

Encoded Feature Matrix (X):
 [[1.0 0.0 0.0 ... 0.0 1 29.85]
 [1.0 0.0 0.0 ... 1.0 34 56.95]
 [1.0 0.0 0.0 ... 1.0 2 53.85]
 ...
 [1.0 0.0 0.0 ... 0.0 11 29.6]
 [0.0 1.0 0.0 ... 1.0 4 74.4]
 [0.0 1.0 0.0 ... 0.0 66 105.65]]
Encoded Target Vector (y):
 [0 0 1 ... 0 1 0]


### Split Dataset into Training and Test Sets

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Train SVM Classifier

In [9]:
from sklearn.svm import SVC

classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

### Make Predictions and Evaluate Model

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred = classifier.predict(X_test)

print("Predictions vs Actual:\n", np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# Calculate the confusion matrix and accuracy
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Confusion Matrix:\n", cm)
print("Accuracy Score:", accuracy)

Predictions vs Actual:
 [[0 0]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 0]]
Confusion Matrix:
 [[950  91]
 [187 181]]
Accuracy Score: 0.8026969481902059
